name: Deploy
on: workflow_dispatch

permissions:
  pages: write
  id-token: write

jobs:
  build:
    name: Build the microsite.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source.
        uses: actions/checkout@v4
      - name: Setup pnpm.
        uses: pnpm/action-setup@v4
      - name: Setup just.
        uses: extractions/setup-just@v3
      - name: Setup node.
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm
      - name: Install dependencies.
        run: pnpm install --frozen-lockfile
      - name: Build.
        run: just build
      - name: Upload artifact.
        uses: actions/upload-pages-artifact@v3
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages.
        id: deploy
        uses: actions/deploy-pages@v4
